{"name": "test_missing_api_key", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.571489 < 0\n +  where 0.571489 = <bound method APICalls.response_time of <pyapi.api.APICalls object at 0x0000026468B57CA0>>()\n +    where <bound method APICalls.response_time of <pyapi.api.APICalls object at 0x0000026468B57CA0>> = <pyapi.api.APICalls object at 0x0000026468B57CA0>.response_time", "trace": "self = <tests.test_api.TestAPI object at 0x0000026468B57CD0>\n\n    def test_missing_api_key(self):\n        api = APICalls(self.url)\n    \n        assert api.get_response_code() == 401\n        print(api.get_response_reason())\n        print(api.response_body())\n        print(api.get())\n>       assert api.response_time() < 0\nE       assert 0.571489 < 0\nE        +  where 0.571489 = <bound method APICalls.response_time of <pyapi.api.APICalls object at 0x0000026468B57CA0>>()\nE        +    where <bound method APICalls.response_time of <pyapi.api.APICalls object at 0x0000026468B57CA0>> = <pyapi.api.APICalls object at 0x0000026468B57CA0>.response_time\n\ntests\\test_api.py:44: AssertionError"}, "attachments": [{"name": "stdout", "source": "e23bfa2d-b49c-4039-8351-d84aef863799-attachment.txt", "type": "text/plain"}], "start": 1681670471412, "stop": 1681670474356, "uuid": "1b4a8bb1-d1bc-4fd7-a5f2-7053ae36882f", "historyId": "4206fb4e04f7d743c39cb465bdf57f11", "testCaseId": "de2d60d44bf17df856ada2e08e601c25", "fullName": "tests.test_api.TestAPI#test_missing_api_key", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestAPI"}, {"name": "host", "value": "LAPTOP-JHMTT23E"}, {"name": "thread", "value": "15624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}